<x-app-layout>

	@section('heading','Update User')

	
		<div class="row g-4 ">
		   
		    <div class="col-lg-5 col-md-8">
		        <div class="card shadow-sm p-4">
				    
				    <div class="card-body">	
				    	<h5 class="card-title">User Account Update</h5>
				    	<p class="mb-2">A User account will be generated for the user with autogenerated password</p>

				    	<form method="POST" action="{{route('users.update',['user' => $user->id])}}">
						@csrf		
						@method('PATCH')    

							<div class="mb-3 form-group">
							    <label class="form-label">First Name</label>
							    <input type="text" class="form-control @error('first_name') is-invalid  @enderror" name="first_name" value="{{ $user->first_name}}">
							    @error('first_name')
							    <div class="invalid-feedback">{{$message}}</div>
							    @enderror
							</div>
							<div class="mb-3 form-group">
							    <label  class="form-label">Last Name</label>
							    <input type="text" class="form-control @error('last_name') is-invalid  @enderror" name="last_name" value="{{ $user->last_name}}">
							    @error('last_name')
							    <div class="invalid-feedback">{{$message}}</div>
							    @enderror
							</div>
							<div class="mb-3 form-group">
							    <label class="form-label">Email Address</label>
							    <input type="email" class="form-control @error('email') is-invalid  @enderror" name="email" value="{{ $user->email}}">
							    @error('email')
							    <div class="invalid-feedback">{{$message}}</div>
							    @enderror
							</div>
							<div class="mb-3 form-group">
							    <label class="form-label">User Role</label>
							    <select class="form-control @error('role') is-invalid @enderror" name="role">
							    	<option disabled >Select</option>
							    	@foreach($roles as $role) 
							    	<option @if($user->roles->pluck('name')[0] == $role) selected @endif >{{$role}}</option>
							    	@endforeach
							    </select>
							    @error('role')
							    <div class="invalid-feedback">{{$message}}</div>
							    @enderror
							</div>

							@if($user->roles->pluck('name')[0] == 'Doctor')
							<div class="mb-3">
							    <label class="form-label">User Permission <small>(Check this textbox if the Doctor is a Chief Doctor)</small></label>
							    <div class="form-check">
								    <input class="form-check-input" type="checkbox" value="true" id="chief_doctor" name="chief_doctor" @if($user->hasPermissionTo('Chief Doctor')) checked @endif>
								    <label class="form-check-label" for="chief_doctor">
								     	Chief Doctor
								    </label>
								 </div>
							    @error('role')
							    <div class="invalid-feedback">{{$message}}</div>
							    @enderror
							</div>
							@endif

							<button class="btn btn-primary text-white" type="submit">Update Account</button>

						</form>  

				    </div><!--//app-card-body-->
				    
				</div><!--//app-card-->
		    </div>

    	</div>
    

</x-app-layout>	
